import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { CartContextProvider } from "./contexts/CartContext";
import HeaderMessage from "./components/headerComponent/HeaderMessage";
import { HeaderMessageContextProvider } from "./contexts/HeaderMessageContext";
import { AuthContextProvider } from "./contexts/AuthContext";
import { getDecodedJwt, getUserById } from "./contexts/actions";
import { getAuthTokenCookie } from "./lib/cookie";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Most E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const existingAuthToken = (await getAuthTokenCookie()) || null;

  let user = null;

  if (existingAuthToken) {
    const decoded = await getDecodedJwt(existingAuthToken);
    if (decoded?.sub) {
      user = await getUserById(decoded.sub);
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContextProvider
          initialToken={existingAuthToken}
          initialUser={user}
        >
          <HeaderMessageContextProvider>
            <HeaderMessage />
            <CartContextProvider>
              <Header />
              {children}
              <Footer />
            </CartContextProvider>
          </HeaderMessageContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
